### ISSUE TITLE
Is Bat supposed to work under Windows?

### ISSUE THREAD

**Issue by swedishmike** [Kitware/bat#45] opened 2017-11-14 08:34 UTC
I tried to do some work on Windows machine and ran into some issues when trying to import logfiles*.

If I follow the 'normal' pattern to import a log file, for example: `conn_df = LogToDataFrame('conn.log')` it crashes out with the following error message:

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-13-c8896a68360f> in <module>()
----> 1 conn_df = LogToDataFrame('conn.log')

~\AppData\Local\Continuum\anaconda3\lib\site-packages\bat\log_to_dataframe.py in __init__(self, log_filename, ts_index)
     22 
     23         # Create a bro reader on a given log file
---> 24         reader = bro_log_reader.BroLogReader(log_filename)
     25 
     26         # Create a Pandas dataframe from reader

~\AppData\Local\Continuum\anaconda3\lib\site-packages\bat\bro_log_reader.py in __init__(self, filepath, delimiter, tail, strict)
     57                             'unknown': lambda x: x}
     58         self.dash_mapper = {'bool': False, 'count': 0, 'int': 0, 'port': 0, 'double': 0.0,
---> 59                             'time': datetime.datetime.fromtimestamp(0), 'interval': datetime.timedelta(seconds=0),
     60                             'string': '-', 'unknown:': '-'}
     61 

OSError: [Errno 22] Invalid argument
```

I did verify that the file is in the current dir etc by a quick:

```
print(os.listdir(os.curdir))
['.ipynb_checkpoints', 'conn.log', 'Connection Time Diagrams.ipynb', 'data']

```
I've tried this with both Jupyter Notebook and on the Python command prompt with the same result.

Using the same approach/files/directory structure works just fine under Linux. I don't really have access to a Mac so haven't been able to test this on that platform.

**Comment by brifordwylie** [comment] 2017-11-24 18:52
Hi @swedishmike it's a bit hard to tell but it looks like the issue is on line 59 of the bro_log_reader.py. I'm guessing it might be either the 'time' or the 'interval' values which use the datetime/timestamp datetime/timedelta calls. Try removing the datetime stuff and just setting those to 0 (might give you an error down the road) but that would tell us that the issue is with one of those datetime calls.

**Comment by swedishmike** [comment] 2017-11-25 19:41
Cheers - I'll give that whirl and poke around a bit and see if I can find something.

**Comment by rohanbapat** [comment] 2017-11-27 02:33
This is the error i think - https://github.com/home-assistant/appdaemon/issues/83

The datetime.datetime.fromtimestamp(0) fails in python 3.6. You should instead try datetime.datetime.fromtimestamp(86400), ie. the number of seconds in 1 day to get it to work.

Hope this helps

**Comment by swedishmike** [comment] 2017-11-27 07:56
@rohanbapat Great catch!

Seems that the bug been open for quite some time as well. https://bugs.python.org/issue29097

**Comment by brifordwylie** [comment] 2017-11-27 21:36
Closing this with the merge of #49

**Closed as completed by brifordwylie** 2017-11-27 21:36 UTC
Labels: bug, feature, help wanted, question

**Comment by swedishmike** [comment] 2017-12-01 22:12
Just tested and can confirm that the new version works on Windows as well now.

Excellent work!
