### ISSUE TITLE
Issue in reading various log files where service column has various values

### ISSUE THREAD

**Issue by sathyaanurag** [Kitware/bat#25] opened 2017-10-05 20:53 UTC
#Operating system - Windows -64 bit
# Jupyter Notebook - Python3

import pandas as pd
import numpy as np
import os
import gzip
from sqlalchemy import create_engine
import pandas as pd
import numpy as np
import sqlalchemy
import re
import sklearn

#pandas python code
reader = bro_log_reader.BroLogReader('storm_conn.log.txt')
storm_df = pd.DataFrame(reader.readrows())
print(storm_df.head())

#Sample log file

#separator \x09
#set_separator	,
#empty_field	(empty)
#unset_field	-
#path	conn
#open	2016-08-01-22-37-35
#fields	ts	uid	id.orig_h	id.orig_p	id.resp_h	id.resp_p	proto	service	duration	orig_bytes	resp_bytes	conn_state	local_orig	local_resp	missed_bytes	history	orig_pkts	orig_ip_bytes	resp_pkts	resp_ip_bytes	tunnel_parents
#types	time	string	addr	port	addr	port	enum	string	interval	count	count	string	bool	bool	count	string	count	count	count	count	set[string]
9.503370	CDHyzp103R7vM3B4Di	10.0.2.104	64324	8.8.8.8	53	udp	dns	-	-	-	S0	-	-	0	D	1	62	0	0	(empty)
10.496136	CYRYDd4hzE1dGQnZ1f	10.0.2.104	64324	8.8.4.4	53	udp	dns	0.001071	34	50	SF	-	-	0	Dd	1	62	1	78	(empty)
10.497730	CYetjF2BLsKlBeXLm	10.0.2.104	54512	8.8.4.4	53	udp	dns	0.000924	34	62	SF	-	-	0	Dd	1	62	1	90	(empty)
6.840918	Ck1imZ29H4UmZErn6k	::	135	ff02::1:ffb8:a750	136	icmp	-	-	-	-	OTH	-	-	0	-	1	64	0	0	(empty)
6.841024	Cv2Hil24LziEl96MV9	fe80::c06e:84b6:bcb8:a750	143	ff02::16	0	icmp	-	0.500843	40	0	OTH	-	-	0	-	2	152	0	0	(empty)
6.840965	CCxmsT35XMpImxttC5	fe80::c06e:84b6:bcb8:a750	133	ff02::2	134	icmp	-	8.001889	24	0	OTH	-	-	0	-	3	168	0	0	(empty)
6.600556	ChcQ99oXrhNvDh1yd	fe80::c06e:84b6:bcb8:a750	546	ff02::1:2	547	udp	-	63.681689	588	0	S0	-	-	0	D	7	924	0	0	(empty)
169.437321	CtV9pH2iCY35WHgzz	10.0.2.104	49157	195.113.232.89	80	tcp	http	0.002621	97	179	SF	-	-	0	ShADadfF	5	309	5	383	(empty)
166.786398	CSN7jI1CwHx1HRri27	fe80::c06e:84b6:bcb8:a750	56899	ff02::1:3	5355	udp	dns	0.098369	44	0	S0	-	-	0	D	2	140	0	0	(empty)
166.786838	CeI4z22y0pPPTNddwl	10.0.2.104	51506	224.0.0.252	5355	udp	dns	0.098144	44	0	S0	-	-	0	D	2	100	0	0	(empty)
167.095598	CTEJ5i3DStut47RUg3	10.0.2.104	137	10.0.2.255	137	udp	dns	1.501089	150	0	S0	-	-	0	D	3	234	0	0	(empty)
169.392290	CMNvAs1ZXKkapRqSIi	10.0.2.104	58727	8.8.8.8	53	udp	dns	0.026124	34	140	SF	-	-	0	Dd	1	62	1	168	(empty)
169.421042	Chciyb4ArzaUY8ybWe	10.0.2.104	59236	8.8.8.8	53	udp	dns	0.001232	34	140	SF	-	-	0	Dd	1	62	1	168	(empty)
147.217168	C9ZaK41wbQmwpoaBM1	::	135	ff02::1:ffb8:a750	136	icmp	-	-	-	-	OTH	-	-	0	-	1	64	0	0	(empty)
147.217241	C8TB0MUzTO5y95Prg	fe80::c06e:84b6:bcb8:a750	133	ff02::2	134	icmp	-	8.000417	24	0	OTH	-	-	0	-	3	168	0	0	(empty)
147.217324	C3v0Am2Hq7PyTLTedh	fe80::c06e:84b6:bcb8:a750	143	ff02::16	0	icmp	-	0.499631	40	0	OTH	-	-	0	-	2	152	0	0	(empty)
166.786946	CPTUIA3tLdBgAvvb8c	10.0.2.2	11	10.0.2.104	0	icmp	-	-	-	-	OTH	-	-	0	-	0	0	0	0	(empty)
167.095837	CMwsTr3sIyp5AMYI9	10.0.2.2	3	10.0.2.104	0	icmp	-	-	-	-	OTH	-	-	0	-	0	0	0	0	(empty)
276.375829	CcrgFD3Ql41215wEkc	10.0.2.104	49158	112.175.184.65	80	tcp	http	0.684047	297	447	SF	-	-	0	ShADadfF	5	509	5	651	(empty)
159.293911	CFBrnw4dpzP9pYSWv8	fe80::c06e:84b6:bcb8:a750	546	ff02::1:2	547	udp	-	63.043744	588	0	S0	-	-	0	D	7	924	0	0	(empty)
277.082464	C1Jt3u5N88vTt65U1	10.0.2.104	49159	112.175.184.100	80	tcp	http	0.644069	280	455	SF	-	-	0	ShADadfF	5	492	5	659	(empty)
277.750904	CAdXNp2YlyVLfcpnoh	10.0.2.104	49160	112.175.184.100	80	tcp	http	0.671336	284	8205	SF	-	-	0	ShADadfF	7	576	9	8569	(empty)
273.482082	CcSdJ11pd1ra1c1hv4	fe80::c06e:84b6:bcb8:a750	57406	ff02::1:3	5355	udp	dns	0.099220	44	0	S0	-	-	0	D	2	140	0	0	(empty)
273.482430	CAtoscHO6Y9zTC9Fd	10.0.2.104	55240	224.0.0.252	5355	udp	dns	0.099009	44	0	S0	-	-	0	D	2	100	0	0	(empty)
273.781786	C57sgV3qGaWmDRhWN5	10.0.2.104	137	10.0.2.255	137	udp	dns	1.501878	150	0	S0	-	-	0	D	3	234	0	0	(empty)
276.090694	CNw3p02HMJ3eB8dKjl	10.0.2.104	54753	8.8.8.8	53	udp	dns	0.283899	41	57	SF	-	-	0	Dd	1	69	1	85	(empty)
277.061944	CI6o9f3MBIEMSzqLa3	10.0.2.104	55875	8.8.8.8	53	udp	dns	0.019935	31	47	SF	-	-	0	Dd	1	59	1	75	(empty)
277.728765	CFMb8KlLQqYZMzGgg	10.0.2.104	57520	8.8.8.8	53	udp	dns	0.021402	35	51	SF	-	-	0	Dd	1	63	1	79	(empty)
273.482522	CBqcyX2WS1vqbl6fZj	10.0.2.2	11	10.0.2.104	0	icmp	-	-	-	-	OTH	-	-	0	-	0	0	0	0	(empty)
273.781914	CsM80i2vCWNHKuSr87	10.0.2.2	3	10.0.2.104	0	icmp	-	-	-	-	OTH	-	-	0	-	0	0	0	0	(empty)
338.427969	CoUu9t4mydgW6PWso8	10.0.2.104	49161	112.175.184.65	80	tcp	http	0.628953	297	447	SF	-	-	0	ShADadfF	5	509	5	651	(empty)
339.057576	C5TxbK1SYv53S3WWN9	10.0.2.104	49162	112.175.184.100	80	tcp	http	0.616180	280	455	SF	-	-	0	ShADadfF	5	492	5	659	(empty)

**Comment by brifordwylie** [comment] 2017-10-05 21:05
@sathyaanurag thanks for the detailed bug report and sample data. I'll get on this right away. So I think there might be a cut/paste issue.. pulling the example data from above I get an error on the third row:

    Conversion Issue for key:orig_ip_bytes value:1 62
    invalid literal for int() with base 10: '1 62'

Can you just attach the file to this ticket instead of cut/paste?

**Comment by brifordwylie** [comment] 2017-10-06 18:33
@sathyaanurag I've spent time trying to fix the file but gave up in frustration. Please attach the demo file instead of cut/pasting it and I'll try to track down the issue.

**Comment by brifordwylie** [comment] 2017-10-16 01:20
@sathyaanurag I cannot reproduce this without an attached file. The cut/paste has random returns when I try to make a new file with it. Can you attach the data file instead of cut/paste?  I'll probably close this in a day or two if we can't get a good reproducible file.

**Comment by brifordwylie** [comment] 2017-10-18 17:43
@sathyaanurag going to close this, feel free to reopen when you get a chance to attached the log that reproduces the error.

**Closed as completed by brifordwylie** 2017-10-18 17:43 UTC
Labels: help wanted
